# Generated by Django 3.0.3 on 2020-06-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_subs_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplatter',
            name='plate_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='pasta_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='dish',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='salads',
            name='salad_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='subs',
            name='sub_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='topping',
            field=models.CharField(max_length=60),
        ),
    ]
